ALTER TABLE `classroom_request`
    ADD COLUMN `participant_count` INTEGER NOT NULL DEFAULT 1,
    MODIFY `status` ENUM('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED') NOT NULL DEFAULT 'DRAFT';
